 development:
   adapter: postgresql
   database: company_development
   username: leelolo12
   password: 130130aa
   encoding: UTF8

 test:
   adapter: postgresql
   database: company_test
   username: leelolo12
   password: 130130aa
   encoding: UTF8

 production:
   adapter: postgresql
   database: company_production
   username: leelolo12
   password: 130130aa
   encoding: UTF8
